sudo: false
language: node_js
matrix:
  fast_finish: true
node_js:
  - "12.18.0"
notifications:
  email: false
before_install:
  - npm i -g npm@6.9.0
install: npm run bootstrap
script:
  - npm run test
