sudo: false
language: node_js
matrix:
  fast_finish: true
node_js:
  - "10.15.3"
notifications:
  email: false
before_install:
  - npm i -g npm@6.9.0
  - npm install -g lerna
install: lerna bootstrap
script: ls packages/bot/node_modules && travis_retry lerna run test
