sudo: false
language: node_js
matrix:
  fast_finish: true
node_js:
  - "10.15.3"
notifications:
  email: false
before_install:
  - npm i -g npm@6.9.0
  - npm install -g lerna
install: lerna bootstrap
script: travis_retry ls packages/deriv-bot/node_modules/deriv-component && lerna run test
