version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  s3: circleci/aws-s3@1.0.13
commands:
  git_checkout_from_cache:
    description: "Git checkout and save cache"
    steps:
      - restore_cache:
          name: "Git restore cache"
          keys:
            - source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - source-v{{ .Environment.CACHE_VERSION }}-
      - run:
          name: "Fetch git tags"
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ== ' >> ~/.ssh/known_hosts
            # Fetch tags if git cache is present
            if [ -e /home/circleci/project/.git ]
            then
              git fetch origin --tags
            fi
      - checkout
      - run:
          name: "Compress git objects"
          command: git gc
      - save_cache:
          name: Git save cache
          key: source-v{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  npm_install_from_cache:
    description: "npm install and save cache"
    steps:
      - run:
          name: "Create cache key"
          command: echo $(find . ./packages/ -maxdepth 2 -name package-lock.json -type f -exec md5sum {} \; | sort -n | md5sum | cut -d' ' -f1) >> CACHE_KEY1
      - restore_cache:
          keys:
            - node-v{{ .Environment.CACHE_VERSION }}-{{ checksum "CACHE_KEY1" }}
      - run:
          name: "Install npm packages"
          command: |
            if [ -d "./node_modules" ]; then
              echo "Found cache. Using cached node_modules."
              node_modules/lerna/cli.js link
            else
              echo "Could not find cache. Bootstrapping..."
              npm run bootstrap             
            fi
      - save_cache:
          name: "Saving node_modules cache"
          key: node-v{{ .Environment.CACHE_VERSION }}-{{ checksum "CACHE_KEY1" }}
          paths:
            # VERIFY_CACHE_FOLDERS_START (DO NOT REMOVE)
            - "node_modules"
            - "packages/account/node_modules"
            - "packages/bot-skeleton/node_modules"
            - "packages/bot-web-ui/node_modules"
            - "packages/components/node_modules"
            - "packages/core/node_modules"
            - "packages/p2p/node_modules"
            - "packages/shared/node_modules"
            - "packages/trader/node_modules"
            - "packages/translations/node_modules"
            # VERIFY_CACHE_FOLDERS_END (DO NOT REMOVE)
  build:
    description: "Build"
    steps:
      - run:
          name: "Build all packages"
          command: npm run build
  compress:
    description: "Compress"
    steps:
      - run:
          name: "Compress"
          command: |
            pushd packages/core/dist/
            tar -cvf artifact.tar *
            mv artifact.tar ${OLDPWD}/
      - run:
          name: "Tag git tag id as artifact identifer"
          command: echo "${CIRCLE_TAG}" > artifact-info.txt
  upload_artifact:
    description: "upload build artifact to s3 bucket"
    steps:
      - s3/copy:
          from: artifact.tar
          to: 's3://${CONTEXT_ARTIFACT_S3_BUCKET}/${CIRCLE_PROJECT_REPONAME}/'
          aws-access-key-id: env_CONTEXT_ARTIFACT_S3_AWS_ACCESS_KEY_ID
          aws-secret-access-key: env_CONTEXT_ARTIFACT_S3_AWS_SECRET_ACCESS_KEY
          aws-region: env_CONTEXT_ARTIFACT_S3_AWS_REGION
          arguments: '--metadata "{\"x-amz-artifact-id\": \"${CIRCLE_TAG}\" }"'
  upload_checksum:
    description: "upload artifact checksum to s3"
    steps:
      - s3/copy:
          from: artifact-info.txt
          to: 's3://${CONTEXT_ARTIFACT_S3_BUCKET}/${CIRCLE_PROJECT_REPONAME}/'
          aws-access-key-id: env_CONTEXT_ARTIFACT_S3_AWS_ACCESS_KEY_ID
          aws-secret-access-key: env_CONTEXT_ARTIFACT_S3_AWS_SECRET_ACCESS_KEY
          aws-region: env_CONTEXT_ARTIFACT_S3_AWS_REGION
  docker_build_push:
    description: "Build and Push image to docker hub"
    parameters:
      docker_image_latest_tag:
        type: string
        default: "latest-staging"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building docker image
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker build -t ${DOCKHUB_ORGANISATION}/deriv-app:${TAG} -t ${DOCKHUB_ORGANISATION}/deriv-app:<< parameters.docker_image_latest_tag >> .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/deriv-app
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_svc_name:
        type: string
        default: "staging-deriv-app"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service deriv-app
          command: |
            TAG=${CIRCLE_TAG:-$CIRCLE_SHA1}
            for SERVER_ID in {1..5}
            do
              KUBE_SERVER_REF="KUBE_SERVER_$SERVER_ID"
              SERVICEACCOUNT_TOKEN_REF="SERVICEACCOUNT_TOKEN_$SERVER_ID"
              CA_CRT_REF="CA_CRT_$SERVER_ID"
              if [ ! -z "${!KUBE_SERVER_REF}" ]
              then
                echo "Deploying to cluster $SERVER_ID"
                CA_CRT="${!CA_CRT_REF}"
                KUBE_SERVER="${!KUBE_SERVER_REF}"
                SERVICEACCOUNT_TOKEN="${!SERVICEACCOUNT_TOKEN_REF}"
                echo $CA_CRT | base64 --decode > ca.crt
                kubectl --server=${KUBE_SERVER} --certificate-authority=ca.crt --token=$SERVICEACCOUNT_TOKEN set image deployment/<< parameters.k8s_svc_name >> << parameters.k8s_svc_name >>=${DOCKHUB_ORGANISATION}/deriv-app:${TAG}
              fi
            done
jobs:
  build_staging:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - docker_build_push
    environment:
      NODE_ENV: staging
  build_production:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - git_checkout_from_cache
      - npm_install_from_cache
      - build
      - compress
      - upload_artifact
      - upload_checksum
      - docker_build_push:
          docker_image_latest_tag: latest
    environment:
      NODE_ENV: staging
  deploy_staging:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - k8s_deploy
  deploy_production:
    docker:
      - image: circleci/node:12.18.0-stretch
    steps:
      - k8s_deploy:
          k8s_svc_name: production-deriv-app
workflows:
  build_deploy_staging:
    jobs:
      - build_staging:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              only: /^dev$/
      - deploy_staging:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              only: /^dev$/
          requires:
            - build_staging
  build_deploy_production:
    jobs:
      - build_production:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
      - deploy_production:
          context: binary-frontend-artifact-upload
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          requires:
            - build_production
