name: Deriv-app Dependency Review
on: 
  pull_request:
    branches:
        - master
jobs:
    dependency_review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
        - name: 'Checkout Repository'
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        - name: 'Dependency Review'
          uses: actions/dependency-review-action@5bbc3ba658137598168acb2ab73b21c432dd411b
          with:
            comment-summary-in-pr: on-failure
            repo-token: ${{ secrets.GITHUB_TOKEN }}
