name: Merge and release to staging
permissions:
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      release_tag_task_url:
          description: "Release Tag task URL(e.g. https://app.clickup.com/t/1**/W*-*)"
          required: true
      skip_circleci_checks:
        description: "Skip checking CircleCI workflow"
        type: boolean
        required: false
      skip_pending_checks:
        description: "Skip waiting for pull request checks"
        type: boolean
        required: false

concurrency:
  group: release_automation_group

jobs:
  release_issues:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Wait for logs to accumulate
        run: |
          sleep 10
      - name: Release issues in Deriv.app
        uses: binary-com/fe-toolbox@v0.0.1
        with:
          release_tag_task_url: ${{ inputs.release_tag_task_url }}
          platform: 'Deriv.app'
          config_path: ./.github/workflows/automationrc.json
          skip_circleci_checks: ${{ inputs.skip_circleci_checks }}
          skip_pending_checks: ${{ inputs.skip_pending_checks }}
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
          CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
