name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Install Playwright Test
      run: |
        cd end-to-end-test
        npm install -D @playwright/test
    - name: Create env file
      run: |
        cd end-to-end-test/
        touch .env
        echo "${{ secrets.PLAYWRIGHT_ENV_FILE }}" > .env
        echo "APP_URL=${{ github.event.deployment_status.target_url }}" >> .env
        echo "CI=true" >> .env
    - name: Run Playwright tests
      run: |
        cd end-to-end-test
        mkdir playwright-json-test-results
        CURRENT_BRANCH=${GITHUB_REF#refs/heads/} sudo npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Upload JSON test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-json-results
        path: playwright-json-test-results
        retention-days: 90
    - name: Download JSON test results
      uses: actions/download-artifact@v3
      if: always()
      with:
        name: playwright-json-results
        path: playwright-json-test-results/
    - name: Extract JSON test results
      run: |
        ls -la
        cd playwright-json-test-results
        unzip -o playwright-json-test-results.zip
        ls -la
