name: Deriv App Staging Workflow
on:
  push:
    branches:
    - rc_*

jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Cloudflare Staging 
    runs-on: Runner_16cores_Deriv-app
    environment: Staging
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: "./.github/actions/setup_node"
    - name: Install Dependencies
      uses: "./.github/actions/npm_install_from_cache"
    - name: Build
      uses: "./.github/actions/build"
      with:
        NODE_ENV: staging
        DATADOG_APPLICATION_ID: ${{ vars.DATADOG_APPLICATION_ID }} 
        DATADOG_CLIENT_TOKEN: ${{ vars.DATADOG_CLIENT_TOKEN }}
        DATADOG_CLIENT_TOKEN_LOGS: ${{ vars.DATADOG_CLIENT_TOKEN_LOGS }}
        DATADOG_SESSION_REPLAY_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_REPLAY_SAMPLE_RATE }}
        DATADOG_SESSION_SAMPLE_RATE: ${{ vars.DATADOG_SESSION_SAMPLE_RATE }}
        DATADOG_SESSION_SAMPLE_RATE_LOGS: ${{ vars.DATADOG_SESSION_SAMPLE_RATE_LOGS }}
        GD_API_KEY: ${{ secrets.GD_API_KEY }}
        GD_APP_ID: ${{ secrets.GD_APP_ID }}
        GD_CLIENT_ID: ${{ secrets.GD_CLIENT_ID }}
        RUDDERSTACK_KEY: ${{ vars.RUDDERSTACK_KEY }}
        REF_NAME: ${{ github.ref_name }}
    - name: Run tests
      run: npm test
    - name: Publish to Cloudflare Pages Staging 
      uses: "./.github/actions/publish_to_pages_staging"
      with:       
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    - name: Build Docker image and push to Docker hub and K8S
      uses: "./.github/actions/build_and_push_docker_image"
      with:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        DOCKERHUB_ORGANISATION: ${{ secrets.DOCKERHUB_ORGANISATION }}
        K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}
        KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
        SERVICEACCOUNT_TOKEN: ${{ secrets.SERVICEACCOUNT_TOKEN }}
        CA_CRT: ${{ secrets.CA_CRT }}
        APP_VERSION: latest-staging
