name: Sync translations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  sync_translations:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Sync translations
        uses: deriv-com/translations/.github/actions/extract_and_sync_translations@main
        with:
          PROJECT_NAME: ${{ env.ACC_R2_PROJECT_NAME }}
          CROWDIN_BRANCH_NAME: staging
          CROWDIN_PROJECT_ID: ${{ secrets.ACC_CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.ACC_R2_CROWDIN_PERSONAL_TOKEN }}
          R2_ACCOUNT_ID: ${{ secrets.ACC_R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.ACC_R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.ACC_R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.ACC_R2_BUCKET_NAME }}
          PROJECT_SOURCE_DIRECTORY: "packages/account/src"